# Generated by Django 5.2.6 on 2025-09-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastnmae',
            new_name='lastname',
        ),
    ]
